// src/settings-preload.js — bridge for the shell settings window.
'use strict';

const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('dshShell', {
  getSettings: () => ipcRenderer.invoke('shell:get-settings'),
  saveSettings: (partial) => ipcRenderer.invoke('shell:save-settings', partial),
  getTheme: () => ipcRenderer.invoke('shell:get-theme'),
  onTheme: (cb) => ipcRenderer.on('shell:theme', (_e, t) => cb(t)),
  pickFolder: (kind) => ipcRenderer.invoke('shell:pick-folder', kind),
  runtimeInfo: () => ipcRenderer.invoke('shell:runtime-info'),
  checkUpdate: () => ipcRenderer.invoke('shell:check-update'),
  applyUpdate: () => ipcRenderer.invoke('shell:apply-update'),
  rollback: () => ipcRenderer.invoke('shell:rollback'),
  openLogDir: () => ipcRenderer.invoke('shell:open-log-dir'),
  backupNow: () => ipcRenderer.invoke('shell:backup-now'),
  backupInfo: () => ipcRenderer.invoke('shell:backup-info'),
  storageInfo: () => ipcRenderer.invoke('shell:storage-info'),
  storageCleanup: () => ipcRenderer.invoke('shell:storage-cleanup'),
  setWorkspace: (ws) => ipcRenderer.invoke('shell:set-workspace', ws),
  pluginsList: () => ipcRenderer.invoke('shell:plugins-list'),
  pluginSearch: (kw) => ipcRenderer.invoke('plugins:search', kw),
  pluginMarket: (force) => ipcRenderer.invoke('plugins:market', force),
  pluginAction: (action, fullName) => ipcRenderer.invoke('shell:plugin-action', action, fullName),
  profileSnapshots: () => ipcRenderer.invoke('shell:profile-snapshots'),
  restoreSnapshot: (id) => ipcRenderer.invoke('shell:restore-snapshot', id),
  safeMode: () => ipcRenderer.invoke('shell:safe-mode'),
  onPluginProgress: (cb) => ipcRenderer.on('plugins:progress', (_e, d) => cb(d)),
  // skills center (C4): SKILL.md packs — market/installed list + actions
  skillsList: (force) => ipcRenderer.invoke('shell:skills-list', force),
  skillsPreview: (fullName) => ipcRenderer.invoke('shell:skills-preview', fullName),
  skillsInstall: (fullName, pick) => ipcRenderer.invoke('shell:skills-install', fullName, pick),
  skillsRemove: (name) => ipcRenderer.invoke('shell:skills-remove', name),
  skillsUpgrade: (name) => ipcRenderer.invoke('shell:skills-upgrade', name),
  skillsImport: (dir, pick) => ipcRenderer.invoke('shell:skills-import', dir, pick),
  onSkillsProgress: (cb) => ipcRenderer.on('skills:progress', (_e, d) => cb(d)),
  restartRuntime: () => ipcRenderer.invoke('shell:restart-runtime'),
  costInfo: () => ipcRenderer.invoke('shell:cost-info'),
  balanceInfo: () => ipcRenderer.invoke('shell:balance-info'),
  balanceRefresh: () => ipcRenderer.invoke('shell:balance-refresh'),
  diagnosticsInfo: () => ipcRenderer.invoke('shell:diagnostics-info'),
  openDiagnostics: () => ipcRenderer.invoke('shell:open-diagnostics'),
  scheduledList: () => ipcRenderer.invoke('shell:scheduled-list'),
  scheduledUpsert: (task) => ipcRenderer.invoke('shell:scheduled-upsert', task),
  scheduledRemove: (id) => ipcRenderer.invoke('shell:scheduled-remove', id),
  remoteStatus: () => ipcRenderer.invoke('remote:status'),
  remotePairing: () => ipcRenderer.invoke('remote:pairing'),
  remoteRevoke: () => ipcRenderer.invoke('remote:revoke'),
  // public remote access (C7): Tailscale detection, cloudflared quick tunnel,
  // and the confirmed-enable flow (the renderer passes confirmed=true only
  // after the public-network warning dialog)
  publicRemoteStatus: (force) => ipcRenderer.invoke('shell:public-remote-status', !!force),
  publicRemoteEnable: (mode, confirmed) => ipcRenderer.invoke('shell:public-remote-enable', mode, confirmed),
  publicRemoteDisable: () => ipcRenderer.invoke('shell:public-remote-disable'),
  tunnelStart: () => ipcRenderer.invoke('shell:tunnel-start'),
  tunnelStop: () => ipcRenderer.invoke('shell:tunnel-stop'),
  modelsList: () => ipcRenderer.invoke('shell:models-list'),
  modelsSave: (profile, apiKey) => ipcRenderer.invoke('shell:models-save', profile, apiKey),
  modelsRemove: (id) => ipcRenderer.invoke('shell:models-remove', id),
  modelsTest: (target) => ipcRenderer.invoke('shell:models-test', target),
  ollamaStatus: () => ipcRenderer.invoke('shell:ollama-status'),
  modelsSetDefault: (provider, model) => ipcRenderer.invoke('shell:models-set-default', provider, model),
  copyText: (text) => ipcRenderer.invoke('shell:copy-text', text),
  scheduledRun: (id) => ipcRenderer.invoke('shell:scheduled-run', id),
  scheduledHistory: () => ipcRenderer.invoke('shell:scheduled-history'),
  scheduledClearHistory: () => ipcRenderer.invoke('shell:scheduled-clear-history'),
  copyAndShow: (text, title, body) => ipcRenderer.invoke('shell:copy-and-show', text, title, body),
  onScheduledChanged: (cb) => ipcRenderer.on('scheduled:changed', () => cb()),
  // long-session center (C3): compaction + AGENTS.md memory files
  compactNow: () => ipcRenderer.invoke('shell:compact-now'),
  compactStatus: () => ipcRenderer.invoke('shell:compact-status'),
  compactHistory: () => ipcRenderer.invoke('shell:compact-history'),
  onCompactStatus: (cb) => ipcRenderer.on('compact:status', (_e, s) => cb(s)),
  memoryGet: (scope) => ipcRenderer.invoke('shell:memory-get', scope),
  memorySave: (scope, content) => ipcRenderer.invoke('shell:memory-save', scope, content),
  memoryDelete: (scope) => ipcRenderer.invoke('shell:memory-delete', scope),
  // IM channels (C5 lifecycle + C6 credentials): card list / toggle /
  // allowlist; configure/test run in the main process so secrets never
  // persist or render in the settings window
  channelsList: () => ipcRenderer.invoke('shell:channels-list'),
  channelsToggle: (id, enabled) => ipcRenderer.invoke('shell:channels-toggle', id, enabled),
  channelsAllowFrom: (id, allowFrom) => ipcRenderer.invoke('shell:channels-allowfrom', id, allowFrom),
  channelsConfigure: (id, values) => ipcRenderer.invoke('shell:channels-configure', id, values),
  channelsTest: (id, values) => ipcRenderer.invoke('shell:channels-test', id, values),
  onChannelsChanged: (cb) => ipcRenderer.on('channels:changed', () => cb()),
});
